RefreshKey: <put a valid refresh key here>
AccessKey: <put an optional access key here>
#URL: http://playground.devicehive.com/api/rest
URL: ws://playground.devicehive.com/api/websocket

DeviceID: go-dbus-gw
DeviceName: Go D-Bus Gateway

NetworkName: <network name>
NetworkDescription: <network description>

LoggingLevel: debug
DH-LoggingLevel: debug
