version: '2'
services:
  dbus:
    build: ./dbus
    network_mode: "host"

  cloud:
    build: ./cloud
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"

  ble:
    build: ./ble
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"
    privileged: true
