version: '2'
services:
  dbus:
    build:
      context: ./dbus
      dockerfile: Dockerfile.armhf
    network_mode: "host"

  cloud:
    build:
      context: ./cloud
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"

  ble:
    build:
      context: ./ble
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"
    privileged: true
