version: '2'
services:
  dbus:
    image: devicehive/iot-dbus:2.0
    build:
      context: ./dbus
      dockerfile: Dockerfile

  cloud:
    image: devicehive/iot-cloud:2.0
    build:
      context: ./cloud
      dockerfile: Dockerfile
    depends_on:
      - dbus
    volumes_from:
      - dbus
    volumes:
      - ./cloud/config.yml:/etc/devicehive-cloud.yml

  ble:
    image: devicehive/iot-ble:2.0
    build:
      context: ./ble
      dockerfile: Dockerfile
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"
    privileged: true

  apps:
    image: devicehive/iot-apps:2.0
    build:
      context: ./apps
      dockerfile: Dockerfile
    command: ./sensortag.py
    depends_on:
      - dbus
      - cloud
      - ble
    volumes_from:
      - dbus
