# TODO: use ${ARCH} environment variable instead of armhf suffix
# to support multiple architectures within the same file!

version: '2'
services:
  dbus:
    build:
      context: ./dbus
      dockerfile: Dockerfile.armhf
    network_mode: "host"

  cloud:
    build:
      context: ./cloud
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"

  ble:
    build:
      context: ./ble
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"
    privileged: true

  examples:
    build:
      context: ./examples
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
      - cloud
      - ble
    volumes_from:
      - dbus
