# TODO: use ${ARCH} environment variable instead of armhf suffix
# to support multiple architectures within the same file!

version: '2'
services:
  dbus:
    image: devicehive/iot-dbus:2.0-armhf
    build:
      context: ./dbus
      dockerfile: Dockerfile.armhf

  cloud:
    image: devicehive/iot-cloud:2.0-armhf
    build:
      context: ./cloud
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
    volumes_from:
      - dbus
    volumes:
      - ./cloud/config.yml:/etc/devicehive-cloud.yml

  ble:
    image: devicehive/iot-ble:2.0-armhf
    build:
      context: ./ble
      dockerfile: Dockerfile.armhf
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"
    privileged: true

  apps:
    image: devicehive/iot-apps:2.0-armhf
    build:
      context: ./apps
      dockerfile: Dockerfile.armhf
    command: ./sensortag.py
    depends_on:
      - dbus
      - cloud
      - ble
    volumes_from:
      - dbus
