version: '2'
services:
  dbus:
    build:
      context: ./dbus
      dockerfile: Dockerfile
    network_mode: "host"

  cloud:
    build:
      context: ./cloud
      dockerfile: Dockerfile
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"

  ble:
    build:
      context: ./ble
      dockerfile: Dockerfile
    depends_on:
      - dbus
    volumes_from:
      - dbus
    network_mode: "host"
    privileged: true

  examples:
    build:
      context: ./examples
      dockerfile: Dockerfile
    depends_on:
      - dbus
      - cloud
      - ble
    volumes_from:
      - dbus
